Functions for using named cronjobs
Stuyk/rebar-altv pull request #138
Opened 2024-08-02 20:41 UTC by KoronGIT

Node-cron is used.

Functions:

create
remove
addTaskToCron
removeTaskFromCron

Usage Example:

`import { useRebar } from '@Server/index.js';

const Rebar = useRebar();
const cronJob = Rebar.useCronJob();

export function task1() {
    alt.log('Task 1');
}

export function task2() {
    alt.log('Task 2');
}

declare global {
    export interface CronJobs {
        'my-cronjob': {
            cronExpression: string;
            tasks: any[];
        };
    }
}

cronJob.create('my-cronjob', '*/5 * * * * *', [task1]);
cronJob.addTaskToCron('my-cronjob', task2);
`

2024-08-03 20:05 UTC, Stuyk requested changes

2024-08-03 20:05 UTC, Stuyk commented on src/main/server/cronjob/index.ts
> +        }
```suggestion
        if (!registeredJobs.has(jobName)) {
            return;
        }
        
        const { job } = registeredJobs.get(jobName);
        job.stop();
        registeredJobs.delete(jobName);
```

2024-08-03 20:05 UTC, Stuyk commented on src/main/server/cronjob/index.ts
> +        }
```suggestion
        if (!registeredJobs.has(jobName)) {
            return;
        }
        
        const { job, cronExpression, tasks } = registeredJobs.get(jobName);
        job.stop();

        tasks.push(task);
        create(jobName, cronExpression, tasks, true);
```

2024-08-03 20:05 UTC, Stuyk commented on src/main/server/cronjob/index.ts
> +    }
```suggestion
    function removeTaskFromCron<K extends keyof CronJobs>(jobName: K, task: () => void) {
        if (!registeredJobs.has(jobName)) {
            return;
        }
        
        const { job, cronExpression, tasks } = registeredJobs.get(jobName);
        job.stop();

        const index = tasks.indexOf(task);
        if (index > -1) {
            tasks.splice(index, 1);
        }

        create(jobName, cronExpression, tasks, true);
    }
```

2024-08-03 20:07 UTC, Stuyk commented
Additionally, could use a documentation page on this.

2024-08-04 15:41 UTC, KoronGIT commented
> Additionally, could use a documentation page on this.

I added documentation

2024-08-05 13:30 UTC, Stuyk commented on docs/useRebar/useCronJob.md
> +Allow plugins to create cronjobs.
```suggestion
This API allows you to create timed events that happen at different intervals based on server time. Such as every 5th minute of the hour, every hour, etc. 
```

2024-08-05 13:30 UTC, merged